# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: mvn build

on:
  push:
    branches: [ development ]
    

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: step1 - checkout develop branck code 
      uses: actions/checkout@v3
      
    - name: step2 - Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: step3 - Build with Maven
      run: mvn clean package -s settings.xml 

    - name: step4 - list generated file list
      run: ls -a
      

    - name: step5 -  observ target folder
      run: |  
        cd target
        ls -a
